# Generated by Django 5.2.10 on 2026-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_uploadhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='avg_flowrate',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='avg_pressure',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='avg_temperature',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='total_equipment',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='type_distribution',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
